framework:
    messenger:
        # Désactiver Messenger pour le moment
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # sync: 'sync://'
        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
