controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
<<<<<<< HEAD
    type: attribute
=======
    type: attribute
>>>>>>> 43fbb94 (Initial project Symfony boutique)
